- name: "installing based on distribution"
  hosts: all
  tasks: 
    - name: "installing with apt"
      apt:
        name: apache2
        state: present
        when: ansible_distribution="Ubuntu"
    - name: "installing apache2 with apk on alpine"
      community.general.apk: 
        name: apache2
        state: latest
        when: ansible_distribution="Alpine"          