- name: "installing apache2 on db hosts"
  hosts: db
  tasks: 
    - name: "updating repositories"
      community.general.apk:
          update_cache: true
    - name: "upgrading packages"
      community.general.apk:
           upgrade: true
    - name: "installing openRC"
      community.general.apk:
      name: openrc           
    - name: "installing apache2"
      community.general.apk:
          name: apache2   
    - name: "starting apache service" 
      ansible.builtin.service:
        name: apache2
        state: started
