- name: "updating cache"
  community.general.apk:
   update_cache: true
- name: "installing apache"
  community.general.apk:
   name: apache2
- name: "starting apache service" 
  ansible.builtin.service:
    name: apache2
    state: started