---
- name: "Install Apache"
  community.general.apk:
    name: apache2
    state: present
#- name: "Start Apache service"
 # service:
  #  name: apache2
   # state: started
  #ignore_errors: true
- name: "starting apache service"
  ansible.builtin.command:
    cmd: /usr/sbin/httpd -D FOREGROUND
- name: "Display post-installation message for Apache"
  debug:
    msg: "Apache installation completed successfully!"
- name: "Copy Apache info HTML file"
  copy:
    src: index.html
    dest: /var/www/localhost/htdocs
    mode: 644
