---
- name: "Install Apache"
  community.general.apk:
    name: apache2
    state: present
- name: "Start Apache service"
  service:
    name: apache2
    state: started
  ignore_error: true 
- name: "Display post-installation message for Apache"
  debug:
    msg: "Apache installation completed successfully!"
- name: "Copy Apache info HTML file"
  copy:
    src: apache_info.html
    dest: /var/www/html/index.html
    mode: 644
