---
- name: "Installing nginx"
  community.general.apk:
    name: nginx
    state: present
- name: "starting nginx service"
  ansible.builtin.command:
    cmd: "nginx -g 'daemon off;'"
  async: 10
  poll: 0
- name: "Display post-installation message for nginx"
  debug:
    msg: "Nginx installation completed successfully!"
- name: "Copy nginx info HTML file"
  copy:
    src: index.html
    dest: /usr/share/nginx/html
    mode: 644